// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XhFLUH3AqdxxdZrdpgJZfqF6Nn-H0y8',
    appId: '1:857385163517:web:029de77ad1a92bdfa4fc94',
    messagingSenderId: '857385163517',
    projectId: 'medigen-210d7',
    authDomain: 'medigen-210d7.firebaseapp.com',
    storageBucket: 'medigen-210d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMhXrrP2SCb-9U9QUkQV9lUfWbZk3XN0',
    appId: '1:857385163517:android:7acc71033721c676a4fc94',
    messagingSenderId: '857385163517',
    projectId: 'medigen-210d7',
    storageBucket: 'medigen-210d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5g_3Xq6GIaELCE_L3eArT43hSXUeYoYU',
    appId: '1:857385163517:ios:a76ff42fcecd2346a4fc94',
    messagingSenderId: '857385163517',
    projectId: 'medigen-210d7',
    storageBucket: 'medigen-210d7.firebasestorage.app',
    androidClientId: '857385163517-52ob27rkstq1ij9t9fiaklir31uqbmar.apps.googleusercontent.com',
    iosClientId: '857385163517-oa8o67o9s8ahbp1ne1n22rl1o5utm2bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.medigen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1XhFLUH3AqdxxdZrdpgJZfqF6Nn-H0y8',
    appId: '1:857385163517:web:adc3412eded7d474a4fc94',
    messagingSenderId: '857385163517',
    projectId: 'medigen-210d7',
    authDomain: 'medigen-210d7.firebaseapp.com',
    storageBucket: 'medigen-210d7.firebasestorage.app',
  );

}